Nico_BlogBundle_homepage:
    pattern:  /
    defaults: { _controller: NicoBlogBundle:Page:index }
    requirements:
        _method:  GET
Nico_BlogBundle_about:
    pattern:  /about
    defaults: { _controller: NicoBlogBundle:Page:about }
    requirements:
        _method:  GET
