Nico_BlogBundle_homepage:
    pattern:  /
    defaults: { _controller: NicoBlogBundle:Page:index }
    requirements:
        _method:  GET
Nico_BlogBundle_about:
    pattern:  /about
    defaults: { _controller: NicoBlogBundle:Page:about }
    requirements:
        _method:  GET
Nico_BlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: NicoBlogBundle:Page:contact }
    requirements:
        _method:  GET
NicoBlogBundle_quark:
    resource: "@NicoBlogBundle/Resources/config/routing/quark.yml"
    prefix:   /quark

