parameters:
#    nico_blog.example.class: Nico\BlogBundle\Example

services:
     markdown:
         class: Nico\BlogBundle\Utils\Markdown
     app.twig.app_extension:
         class: Nico\BlogBundle\Twig\AppExtension
         arguments: ["@markdown"]
         public:    false
         tags:
             - { name: twig.extension }
