Nico\BlogBundle\Entity\Quark:
  type: entity
  table: quark
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    content:
      type: text
    categories_csv:
      type: string
    parent:
      type: integer
    user_id:
      type: integer
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true
  manyToMany:
    groups:
      targetEntity: Category
      joinTable:
        name: quark_category
        joinColumns:
          quark_id:
            referencedColumnName: id
        inverseJoinColumns:
          category_id:
            referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ doSetCreatedAtValue ]
    preUpdate: [ doSetUpdatedAtValue ]


