nico_user:
    resource: "@NicoUserBundle/Resources/config/routing.yml"
    prefix:   /

nico_blog:
    resource: "@NicoBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
