<?php
namespace Nico\BlogBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * QuarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuarkRepository extends EntityRepository
{
  public function findAllQuarkAndTagsArray()
  {
    $query = $this->createQueryBuilder('a')
      ->leftJoin('a.tags', 't')
      ->addSelect('t')
      ->getQuery();
    $res = $query->getArrayResult();
    return $res;
  }
  public function findAllQuarkAndTags()
  {
    $query = $this->createQueryBuilder('a')
      ->leftJoin('a.tags', 't')
      ->addSelect('t')
      ->getQuery();
    $res = $query->getResult();
    return $res;
  }
}
