<?php
namespace Nico\BlogBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
  public function findAllValid()
  {
    $query = $this->createQueryBuilder('a')
      ->distinct('name')
      ->getQuery();
    $res = $query->getResult();
    return $res;
  }
}

