parameters:
#    nico_user.example.class: Nico\UserBundle\Example

services:
#    nico_user.example:
#        class: %nico_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
